### PR TITLE
Intro to Solana course

### PR DESCRIPTION
**Pull request by pkozelka**
This is the Solana intro course, based on simple demos from Solana repos.

TODO

* [x] The Rust service
* [x] Lessons code
* [ ] Lessons text

Notes: common commands are in `Makefile`, they are probably easy to transfer into `package.json` or something else
- build the docker image: `make docker-build`
- run the container (production mode - info logging, built-in content): `make run`
- run the container (debug mode - debug logging, content mounted from repo): `make debug`

### CODE REVIEW

**Comment by romario333** [comment]
Move all rust related stuff together with Makefile  to either `solana-runner` or `packages/solana-runner` to keep it consistent with our other repos.

**Comment by romario333** [comment]
Please add numeric prefix to lesson slug. Especially `01-introduction` is important. We have already sent out a link with this slug to Solana.

**Comment by romario333** [comment]
Returns 404 for `/v1/solve/`. Should handle both, `/v1/solve` and `/v1/solve/`

**Comment by pkozelka** [comment]
all comments addressed; for now, I only numbered first lesson; I will later add numeric prefix to others

**Pull request merged**
